/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 17 11:46:55 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Bessj_ESTest extends Bessj_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      double double0 = bessj0.bessj(2097, (-1.0));
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      double double0 = bessj0.bessj(675, 4053.9452018567);
      assertEquals((-0.003521033783579464), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      double double0 = bessj0.bessj(314, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      // Undeclared exception!
      try { 
        bessj0.bessj(0, 4902.998139577095);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Index n less than 2 in bessj
         //
         verifyException("Bessj", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      double double0 = bessj0.bessj(1074, (-1.0));
      assertEquals(0.0, double0, 0.01);
  }
}
