/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 23 21:26:53 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Bessj_ESTest extends Bessj_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      double double0 = bessj0.bessj(2, 6);
      assertEquals((-0.24287321254500593), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      double double0 = bessj0.bessj(1532, (-1133.2277915399895));
      assertEquals(7.092941416991082E-98, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      double double0 = bessj0.bessj(693, (-3133.98));
      assertEquals(0.007867979731660285, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      double double0 = bessj0.bessj(370, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Bessj bessj0 = new Bessj();
      // Undeclared exception!
      try { 
        bessj0.bessj((-1), (-1));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Index n less than 2 in bessj
         //
         verifyException("Bessj", e);
      }
  }
}
