/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 17 11:25:51 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChunkedLongArray_ESTest extends ChunkedLongArray_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray(1);
      chunkedLongArray0.add(1);
      chunkedLongArray0.add(1L);
      chunkedLongArray0.sort();
      assertEquals(2, chunkedLongArray0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray(0);
      // Undeclared exception!
      try { 
        chunkedLongArray0.set((long[]) null, 0, 0, 1377);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray(0);
      long[] longArray0 = new long[6];
      chunkedLongArray0.set(longArray0, 1, 1, 1);
      assertEquals(3, chunkedLongArray0.capacity());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray((-2149));
      chunkedLongArray0.set((long[]) null, (-1), (-2149), (-1));
      assertEquals(0, chunkedLongArray0.size());
      assertEquals(0, chunkedLongArray0.capacity());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray(1);
      // Undeclared exception!
      try { 
        chunkedLongArray0.set(chunkedLongArray0, 1, 20, 20);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray(1);
      chunkedLongArray0.set(chunkedLongArray0, 1, 20, (-1754));
      assertEquals(0, chunkedLongArray0.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray(0);
      // Undeclared exception!
      try { 
        chunkedLongArray0.get(0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 requested with array length 0
         //
         verifyException("ChunkedLongArray", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray((-2149));
      String string0 = chunkedLongArray0.toString();
      assertEquals("ChunkedLongArray(0 entries, 0 chunks, 0MB)", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray(1407);
      int int0 = chunkedLongArray0.capacity();
      assertEquals(0, int0);
      assertEquals(0, chunkedLongArray0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = ChunkedLongArray.memStats();
      //  // Unstable assertion: assertEquals("Allocated memory: 0MB, Allocated unused memory: 0MB, Heap memory used: 96MB, Max memory: 0MB", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray();
      assertEquals(0, chunkedLongArray0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray(1);
      chunkedLongArray0.add(1781L);
      chunkedLongArray0.add((-1L));
      chunkedLongArray0.sort();
      assertEquals(2, chunkedLongArray0.size());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ChunkedLongArray chunkedLongArray0 = new ChunkedLongArray((-2149));
      int int0 = chunkedLongArray0.size();
      assertEquals(0, int0);
  }
}
