/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 08 20:48:22 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HSLColor_ESTest extends HSLColor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.brighten(0.7072096F);
      hSLColor0.setSaturation((-786));
      hSLColor0.initHSLbyRGB((-786), (-786), 2808);
      hSLColor0.initHSLbyRGB(2808, (-786), 417);
      hSLColor0.blend(2808, 2808, 2145105482, 0.7072096F);
      assertEquals(1755, hSLColor0.getGreen());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.setSaturation((-1));
      assertEquals(0, hSLColor0.getHue());
      assertEquals(0, hSLColor0.getGreen());
      assertEquals(0, hSLColor0.getBlue());
      assertEquals(0, hSLColor0.getSaturation());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.brighten(0.0F);
      assertEquals(0, hSLColor0.getBlue());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.setLuminence(0);
      hSLColor0.setLuminence((-677));
      hSLColor0.getHue();
      hSLColor0.setSaturation(0);
      assertEquals(0, hSLColor0.getGreen());
      assertEquals(0, hSLColor0.getBlue());
      assertEquals(0, hSLColor0.getSaturation());
      assertEquals(0, hSLColor0.getHue());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.setHue(1257);
      hSLColor0.initHSLbyRGB(1257, (-3315), 1257);
      hSLColor0.brighten(1.0F);
      int int0 = hSLColor0.getSaturation();
      assertEquals(0, hSLColor0.getBlue());
      assertEquals((-566), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.initHSLbyRGB(0, 0, 0);
      hSLColor0.setHue((-1620));
      int int0 = hSLColor0.getRed();
      assertEquals(165, hSLColor0.getHue());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.initRGBbyHSL(0, 255, 1863);
      int int0 = hSLColor0.getRed();
      assertEquals(255, hSLColor0.getGreen());
      assertEquals(255, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.brighten((-1.0F));
      int int0 = hSLColor0.getLuminence();
      assertEquals(0, int0);
      
      hSLColor0.blend(0, 0, 0, (-1.0F));
      hSLColor0.setHue(0);
      assertEquals(0, hSLColor0.getGreen());
      assertEquals(0, hSLColor0.getSaturation());
      assertEquals(0, hSLColor0.getHue());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      int int0 = hSLColor0.getSaturation();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.blend((-700), (-700), (-3476), 286.69F);
      int int0 = hSLColor0.getHue();
      assertEquals((-700), hSLColor0.getRed());
      assertEquals(42, int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.initRGBbyHSL(255, 255, (-3547));
      assertEquals(255, hSLColor0.getSaturation());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.setHue(261);
      hSLColor0.setLuminence(0);
      hSLColor0.setLuminence(1488);
      hSLColor0.setHue(0);
      assertEquals(0, hSLColor0.getHue());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.setHue(1075);
      hSLColor0.getBlue();
      hSLColor0.setLuminence(0);
      assertEquals(55, hSLColor0.getHue());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.initHSLbyRGB((-6473), 1, 0);
      hSLColor0.getGreen();
      hSLColor0.brighten((-394.098F));
      assertEquals(255, hSLColor0.getLuminence());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.setSaturation(2869);
      hSLColor0.initHSLbyRGB(2869, (-1850), 2869);
      int int0 = hSLColor0.getRed();
      assertEquals(2869, hSLColor0.getBlue());
      assertEquals(2869, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      int int0 = hSLColor0.getLuminence();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.reverseColor();
      assertEquals(127, hSLColor0.getHue());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      int int0 = hSLColor0.getBlue();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.setSaturation(171);
      hSLColor0.brighten(171);
      assertEquals(171, hSLColor0.getSaturation());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HSLColor hSLColor0 = new HSLColor();
      hSLColor0.setHue((-42));
      hSLColor0.blend((-42), (-42), 143, 143);
      assertEquals((-42), hSLColor0.getRed());
  }
}
