/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 08 20:27:51 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SubjectParser_ESTest extends SubjectParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      SubjectParser.main(stringArray0);
      SubjectParser subjectParser0 = new SubjectParser("m,J{mkv^[/]Y>_i/N");
      String string0 = subjectParser0.getRangeString();
      assertNotNull(string0);
      assertEquals("[/]", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubjectParser subjectParser0 = new SubjectParser("Uy5)");
      subjectParser0.getTitle();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "Uy5)";
      stringArray0[1] = "Uy5)";
      stringArray0[2] = "S{&BjWY$sq9B`%=";
      stringArray0[3] = "Uy5)";
      stringArray0[4] = "Uy5)";
      stringArray0[5] = "Uy5)";
      stringArray0[6] = "Uy5)";
      stringArray0[7] = "Uy5)";
      stringArray0[8] = "Uy5)";
      SubjectParser.main(stringArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SubjectParser subjectParser0 = new SubjectParser("V?aF|A(x/)__i[~}");
      int int0 = subjectParser0.getThisRange();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        SubjectParser.main(stringArray0);
        fail("Expecting exception: System.SystemExitException");
      
      } catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SubjectParser subjectParser0 = new SubjectParser("[]bxiYvV8OIT'n");
      String string0 = subjectParser0.getTitle();
      assertNotNull(string0);
      assertEquals("bxiYvV8OIT'n", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[15];
      SubjectParser.main(stringArray0);
  }
}
