/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 19 09:23:33 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TokenDispenser_ESTest extends TokenDispenser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser(")<");
      assertFalse(tokenDispenser0.tokenIsRightParen());
      
      tokenDispenser0.nextToken();
      boolean boolean0 = tokenDispenser0.tokenIsRightParen();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("|0j9)QbW2YK^<H>iLd8");
      boolean boolean0 = tokenDispenser0.tokenIsRightParen();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("(@ihw-)X{&");
      assertFalse(tokenDispenser0.tokenIsLeftParen());
      
      tokenDispenser0.nextToken();
      boolean boolean0 = tokenDispenser0.tokenIsLeftParen();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("|0j9)QbW2YK^<H>iLd8");
      boolean boolean0 = tokenDispenser0.tokenIsLeftParen();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("x/6A");
      tokenDispenser0.advance();
      tokenDispenser0.advance();
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertEquals(47, tokenDispenser0.ttype);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("*r!189/@");
      assertFalse(tokenDispenser0.tokenIsOperator());
      
      tokenDispenser0.advance();
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("-");
      assertFalse(tokenDispenser0.tokenIsOperator());
      
      tokenDispenser0.nextToken();
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("|0j9)QbW2YK^<H>iLd8");
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("#x/#6Ab");
      tokenDispenser0.advance();
      tokenDispenser0.advance();
      tokenDispenser0.getToken();
      assertTrue(tokenDispenser0.tokenIsWord());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("|0j9)QbW2YK^<H>iLd8");
      tokenDispenser0.advance();
      tokenDispenser0.advance();
      tokenDispenser0.getToken();
      assertEquals((-2), tokenDispenser0.ttype);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("");
      assertFalse(tokenDispenser0.tokenIsEOF());
      
      tokenDispenser0.nextToken();
      tokenDispenser0.getToken();
      assertTrue(tokenDispenser0.tokenIsEOF());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("|0j9)QbW2YK^<H>iLd8");
      Object object0 = tokenDispenser0.getToken();
      assertEquals('\uFFFC', object0);
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("rg+L<BD:P2mjhGg");
      tokenDispenser0.advance();
      assertFalse(tokenDispenser0.tokenIsOperator());
      
      tokenDispenser0.nextToken();
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("95^@zY5[SVi\u0006y.{_");
      char char0 = tokenDispenser0.getChar();
      assertEquals('\uFFFC', char0);
  }
}
