/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 17 12:04:51 GMT 2017
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TokenDispenser_ESTest extends TokenDispenser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("7Y83nFGB#@");
      assertFalse(tokenDispenser0.tokenIsRightParen());
      
      tokenDispenser0.ttype = 41;
      boolean boolean0 = tokenDispenser0.tokenIsRightParen();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("end of input");
      boolean boolean0 = tokenDispenser0.tokenIsRightParen();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("end of input");
      boolean boolean0 = tokenDispenser0.tokenIsLeftParen();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("end of input");
      assertFalse(tokenDispenser0.tokenIsOperator());
      
      tokenDispenser0.ttype = 47;
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser(">");
      assertFalse(tokenDispenser0.tokenIsOperator());
      
      tokenDispenser0.ttype = 45;
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("end of input");
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("KvXD*F>oq");
      assertFalse(tokenDispenser0.tokenIsOperator());
      
      tokenDispenser0.ttype = 43;
      boolean boolean0 = tokenDispenser0.tokenIsOperator();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("Zi([<G_!4(/i_4r");
      assertFalse(tokenDispenser0.tokenIsWord());
      
      tokenDispenser0.advance();
      tokenDispenser0.getToken();
      assertTrue(tokenDispenser0.tokenIsWord());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("4n");
      tokenDispenser0.advance();
      tokenDispenser0.getToken();
      assertEquals(4.0, tokenDispenser0.getNumber(), 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("end of input");
      Object object0 = tokenDispenser0.getToken();
      assertNotNull(object0);
      assertEquals('\uFFFC', object0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("");
      assertFalse(tokenDispenser0.tokenIsEOF());
      
      tokenDispenser0.advance();
      tokenDispenser0.getToken();
      assertTrue(tokenDispenser0.tokenIsEOF());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TokenDispenser tokenDispenser0 = new TokenDispenser("end of input");
      char char0 = tokenDispenser0.getChar();
      assertEquals('\uFFFC', char0);
  }
}
